config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/faqs', to: 'static_pages#faqs'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get 'subscribe', to: 'subscribers#new'
  resources :subscribers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  # TODO add support for International numbers
  VALID_PHONE_NUMBER_REGEX = /\+\d{11}/

  validates :first_name, presence: true, length: { maximum: 50 }
  validates :last_name, presence: true, length: { maximum: 50 }

  validates :phone_number, presence: true, length: { is: 12 }, format: { with: VALID_PHONE_NUMBER_REGEX }, uniqueness: true

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def faqs
  end

  def contact
  end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  def show
    @subscriber = Subscriber.find(params[:id])
  end

  def new
    @subscriber = Subscriber.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "It's Walk Time"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/layouts/_bootstrap_default.html.erb
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="">

app/views/layouts/_container.html.erb
<div class="container">
  <%= render 'layouts/header' %>
  <main role="main">
    <%= yield %>
  </main>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <p>&copy; Daniel Torrecillas 2017</p>
</footer>

app/views/layouts/_header.html.erb
<header class="header clearfix">
<nav>
  <ul class="nav nav-pills float-right">
    <li class="nav-item">
    <!-- This is how Bootstrap's "Narrow Jumbotron" shows first nav item, for coloring, but I can't get the switchthing to work when other pages are active. Revisit this. 
    <%= link_to root_path, class: "nav-link active" do %>
    Home <span class="sr-only">(current)</span>
    <% end %>
    -->
    <%= link_to "Home", root_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
    <%= link_to "About", about_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
    <%= link_to "FAQs", faqs_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
    <%= link_to "Contact", contact_path, class: "nav-link" %>
    </li>
  </ul>
</nav>
<h3 class="text-muted">It's Walk Time</h3>
</header> 

app/views/layouts/_html5_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/bootstrap_default' %>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/html5_shim' %>
  </head>
  <body>
    <%= render 'layouts/container' %>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About")%>
<h1>About</h1>
<p>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ut mi molestie, sodales orci in, tempus lorem.
Morbi fermentum, dui et dapibus varius, nibh elit accumsan leo, in sagittis sem lorem eget libero. Curabitur
placerat varius nulla, quis tristique quam. Nulla nisi felis, dictum quis mollis a, tincidunt eu ante. Morbi
pulvinar risus ac eros auctor condimentum. Duis augue lacus, aliquet vel lectus in, fermentum hendrerit ipsum.
Sed eu metus consequat dolor elementum ultrices. Maecenas hendrerit iaculis magna sed vestibulum. Maecenas vitae
nulla dolor. Morbi vel lectus in orci interdum laoreet sed facilisis erat.
</p>
<p>
Integer auctor, ipsum ut feugiat bibendum, velit massa tristique tellus, tempus sodales nisl felis quis turpis.
Proin eget lectus ut turpis aliquet accumsan. Nulla vel interdum ante, ut maximus nisl. Nulla nulla sapien,
vehicula id iaculis sit amet, hendrerit sit amet mauris. Donec venenatis libero mi, vitae suscipit dolor ullamcorper
faucibus. Nullam tristique nunc in dui egestas feugiat. Phasellus faucibus ante id nunc porta, in viverra metus
mattis. Donec mauris sapien, porta sed dui vel, auctor laoreet ligula.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ut mi molestie, sodales orci in, tempus lorem.
Morbi fermentum, dui et dapibus varius, nibh elit accumsan leo, in sagittis sem lorem eget libero. Curabitur
placerat varius nulla, quis tristique quam. Nulla nisi felis, dictum quis mollis a, tincidunt eu ante. Morbi
pulvinar risus ac eros auctor condimentum. Duis augue lacus, aliquet vel lectus in, fermentum hendrerit ipsum.
Sed eu metus consequat dolor elementum ultrices. Maecenas hendrerit iaculis magna sed vestibulum. Maecenas vitae
nulla dolor. Morbi vel lectus in orci interdum laoreet sed facilisis erat.
</p>
<p>
Integer auctor, ipsum ut feugiat bibendum, velit massa tristique tellus, tempus sodales nisl felis quis turpis.
Proin eget lectus ut turpis aliquet accumsan. Nulla vel interdum ante, ut maximus nisl. Nulla nulla sapien,
vehicula id iaculis sit amet, hendrerit sit amet mauris. Donec venenatis libero mi, vitae suscipit dolor ullamcorper
faucibus. Nullam tristique nunc in dui egestas feugiat. Phasellus faucibus ante id nunc porta, in viverra metus
mattis. Donec mauris sapien, porta sed dui vel, auctor laoreet ligula.
</p>

app/views/static_pages/faqs.html.erb
<% provide(:title, "FAQs") %>
<h1>FAQs</h1>
<p>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ut mi molestie, sodales orci in, tempus lorem.
Morbi fermentum, dui et dapibus varius, nibh elit accumsan leo, in sagittis sem lorem eget libero. Curabitur
placerat varius nulla, quis tristique quam. Nulla nisi felis, dictum quis mollis a, tincidunt eu ante. Morbi
pulvinar risus ac eros auctor condimentum. Duis augue lacus, aliquet vel lectus in, fermentum hendrerit ipsum.
Sed eu metus consequat dolor elementum ultrices. Maecenas hendrerit iaculis magna sed vestibulum. Maecenas vitae
nulla dolor. Morbi vel lectus in orci interdum laoreet sed facilisis erat.
</p>
<p>
Integer auctor, ipsum ut feugiat bibendum, velit massa tristique tellus, tempus sodales nisl felis quis turpis.
Proin eget lectus ut turpis aliquet accumsan. Nulla vel interdum ante, ut maximus nisl. Nulla nulla sapien,
vehicula id iaculis sit amet, hendrerit sit amet mauris. Donec venenatis libero mi, vitae suscipit dolor ullamcorper
faucibus. Nullam tristique nunc in dui egestas feugiat. Phasellus faucibus ante id nunc porta, in viverra metus
mattis. Donec mauris sapien, porta sed dui vel, auctor laoreet ligula.
</p>

app/views/static_pages/home.html.erb
<div class="jumbotron">
  <h1 class="display-3">Jumbotron heading</h1>
  <p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
  <p><%= link_to "Subscribe", subscribe_path, class: "btn btn-lg btn-success", role: "button"%></p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
  <h4>Subheading</h4>
  <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

  <h4>Subheading</h4>
  <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>

  <h4>Subheading</h4>
  <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
  </div>

  <div class="col-lg-6">
  <h4>Subheading</h4>
  <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

  <h4>Subheading</h4>
  <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>

  <h4>Subheading</h4>
  <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
  </div>
</div>

app/views/subscribers/new.html.erb
<% provide(:title, 'Subscribe') %>
<h1>Subscribe</h1>
<%= form_for(@subscriber) do |form| %>
  <%= form.label :first_name %>
  <%= form.text_field :first_name %>

  <%= form.label :last_name %>
  <%= form.text_field :last_name %>

  <%= form.label :phone_number %>
  <%= form.telephone_field :phone_number %>

  <%= form.label :password %>
  <%= form.password_field :password %>

  <%= form.label :password_confirmation, "Confirm password" %>
  <%= form.password_field :password_confirmation %>

  <%= form.submit "Create my account", class: "btn btn-lg btn-success" %>
<% end %>

app/views/subscribers/show.html.erb
<% provide(:title, @subscriber.full_name) %>
<%= @subscriber.full_name %>